### ISSUE TITLE
爬虫在什么地方

### ISSUE THREAD

**Issue by ryan1000** [dkvirus/py-novel#18]
爬虫在什么地方

**Comment by dkvirus** [comment]
`server_python` 工程整了爬虫，在 reptile 目录下面几个文件就是，主要爬取`小说分类`、`小说信息`、`章节` 等信息。

`server_node_express` 工程舍弃了爬取内容存库的思路。当你要看某一本小说的某一章节时，临时请求该章节地址爬取内容返回给客户端进行展示。考虑一般小说都几千章，全部存到数据库太大了，我买的云服务器并没有多少空间，而且临时爬取内容操作更简单。涉及爬虫内容为 `src/routes` 目录下的 `novel.js` 和 `search.js`。
