### ISSUE TITLE
无法注册，验证接口返回9999

### ISSUE THREAD

**Issue by DarkMario** [dkvirus/py-novel#24]
并且也没有短信发送过来，用你给出的DEMO也无法注册，接收不到短信。flutter和安卓原生都是

**Comment by dkvirus** [comment]
服务端添加jwt认证后，目前小程序的接口已经修改了，flutter和安卓原生还没改。最近我在找工作，太忙了。不过谢谢你的提问，这几天我会把flutter和android接口也换一下。

**Comment by dkvirus** [comment]
@DarkMario [flutter开发的android apk 已经修改了 jwt 认证接口](https://github.com/dkvirus/py-novel/releases/tag/0.3.0)
