### ISSUE TITLE
老哥你的小程序是怎么上架的?

### ISSUE THREAD

**Issue by DarkMario** [dkvirus/py-novel#27]
为何我多次上架都提示我需要资质...

1:小程序内容不符合规则:
(1):你好，贵方小程序涉及提供在线阅读小说服务，小说属个人主体小程序未开放类目，建议申请企业主体小程序

**Comment by dkvirus** [comment]
抱歉，最近忙结婚，才看到。

小程序上架选择的是效率>信息查询。其它流程都是常规操作，不知道有没有解答你的问题。
