### ISSUE TITLE
您好！node版本运行后api访问一直是999

### ISSUE THREAD

**Issue by gutoushe233** [dkvirus/py-novel#33]
请问，您的config.js文件里面是不是还有其它验证的代码？我按照您的说明，添加了数据库信息，发现好了一个端口号；然后运行成功后，访问/api/v2之类的url一直是验证错误，999；您可不可以贴一下您的config配置文件看看？谢谢！

**Comment by dkvirus** [comment]
@gutoushe233  感谢您的反馈。

已经更新了 README.md 文件，附上了完整的 config.js 配置。

**Comment by gutoushe233** [comment]
谢谢！
